# Generated by Django 3.1.5 on 2021-01-06 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_auto_20210106_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
